server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: botanical-traceability-backend
  profiles:
    active: dev
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000 # 24 hours
  blockchain:
    rpc-url: ${BLOCKCHAIN_RPC_URL:https://eth-sepolia.g.alchemy.com/v2/alch_c8cTls0nqnvrEzVlYREFE}
    contract-address: ${BLOCKCHAIN_CONTRACT_ADDRESS:0x2B04B82dD07F1938E74b0CDCA9Fa5693Df147a87}
    network-name: ${BLOCKCHAIN_NETWORK_NAME:Ethereum Sepolia Testnet (Chain ID 11155111)}
    private-key: ${BLOCKCHAIN_RELAYER_PRIVATE_KEY:}
  ipfs:
    gateway-url: https://gateway.pinata.cloud/ipfs/
    mock-mode: true
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://localhost:3000
      - http://127.0.0.1:5173

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
